//
//  NotifycationManager.swift
//  MyRill
//
//  Created by 钟凡 on 16/6/3.
//
//

import UIKit


public let REFRESH_TASK_NOTIFICATION = "REFRESH_TASK_NOTIFICATION"

public let TASK_OR_MISSION_EDIT_NOTIFICATION = "TASK_OR_MISSION_EDIT_NOTIFICATION"

public let PROFESSION_NOTIFICATION = "PROFESSION_NOTIFICATION"

public let REMARK_NOTIFICATION = "REMARK_NOTIFICATION"

public let REFRESH_DIALOGUE_NOTIFICATION = "REFRESH_DIALOGUE_NOTIFICATION"

public let UPDATE_USER_INFO = "UPDATE_USER_INFO"

public let CHANGE_ROOTVIEWCONTROLLER = "CHANGE_ROOTVIEWCONTROLLER"


