//
//  NotifycationManager.swift
//  MyRill
//
//  Created by 钟凡 on 16/6/3.
//
//

import UIKit

open class NotificationManager: NSObject {
    static let REFRESH_TASK_NOTIFICATION = "REFRESH_TASK_NOTIFICATION"
    
    static let TASK_OR_MISSION_EDIT_NOTIFICATION = "TASK_OR_MISSION_EDIT_NOTIFICATION"
    
    static let PROFESSION_NOTIFICATION = "PROFESSION_NOTIFICATION"
    
    static let REMARK_NOTIFICATION = "REMARK_NOTIFICATION"
    
    static let REFRESH_DIALOGUE_NOTIFICATION = "REFRESH_DIALOGUE_NOTIFICATION"
    
    static let UPDATE_USER_INFO = "UPDATE_USER_INFO"
    
    static let CHANGE_ROOTVIEWCONTROLLER = "CHANGE_ROOTVIEWCONTROLLER"
}
